baseURL: informaticore.github.io/thngs-website/
languageCode: de-de
title: THNGS.
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
#canonifyURLs: true
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo.png
    link: /
    # Default width/height. Uncomment if you need to change
    width: 110
    #height: 242
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Website under construction
    # Hero subtitle (optional)
    subtitle: Here you will find informations about our producs soon. If you want get informed once we launched feel free to join our mailing list
    # Button text
    buttontext: Keep me posted!
    # Where the main hero button links to
    buttonlink: https://forms.gle/9qi35Fmpjp2SeMne9
    # Hero image (from static/images/___)
    image: illustrations/tst_ff_scaled.jpg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Products
    sublinks:
    - title: Environment!Thing
      url: /product/thread_sensortag
    # - title: Motion Tag
    #   url: /
    # - title: Trick Tracker
    #   url: /
  - title: About Us
    url: /aboutus

  section1:
    title: Open-Source is key
    subtitle: free the world
    tiles:
    - title: Tindie Shop
      icon: tindie
      text: We sell our products on Tindie
      url: https://www.tindie.com/stores/informatic0re/
      buttonText: Go to Shop
    - title: OpenThread compatible
      icon: ot-logo
      text: Some of our products using the OpenThread network
      url: https://openthread.io/
      buttonText: OpenThread Website
    - title: Open Source Hardware
      icon: oshw-logo
      text: We believe in open-source
      url: https://www.oshwa.org/
      buttonText: OSHWA

  # section2:
  #   title: You're here because you want the best
  #   subtitle: And we know it
  #   features:
  #   - title: Powerful and unified interface
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     # Icon (from /images/illustrations/icons/___.svg)
  #     icon: laptop-globe
  #   - title: Cross-device synchronisation
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: doc-sync
  #   - title: Nomad system
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: mobile-feed
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  # section5: true

  footer:
    # Logo (from /images/logos/___)
    logo: logo.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/Informaticore
      # Icons are from Font Awesome
      icon: github
    # - link: https://dribbble.com/#
    #   icon: dribbble
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://twitter.com/lucperkins
    #   icon: twitter
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: true
    # quicklinks:
    #   column1:
    #     title: "Product"
    #     links:
    #     - text: Products
    #       link: /
    #     - text: Press
    #       link: /
    #     - text: AGB
    #       link: /agb
    #   column2:
    #     title: "Docs"
    #     links:
    #     - text: Datasheets
    #       link: /
    #     - text: How To's
    #       link: /
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
